### ISSUE TITLE
Do .rst documentation for clip_shp function in clip.py and .rst documenation for normalized_diff function in spatial.py

### ISSUE THREAD

**Issue by windnage** [earthlab/earthpy#57] opened 2018-10-24 20:59 UTC
## Identify the Documentation Element That You Propose to Update
* The .rst documentation for the clip_shp function is missing. 
* The .rst documentation for the normalized_diff function is missing.  

## Please Identify Your Proposed Changes Below
I propose adding this .rst documentation for both functions identified above.

**Comment by lwasser** [comment] 2018-10-25 01:05
great submission @windnage . please move forward with submitting a PR with these changes!

**Comment by lwasser** [comment] 2018-10-30 18:04
This has been merged and the issue is now resolved!

**Closed by lwasser** 2018-10-30 18:04 UTC
Labels: good first issue, pr requested
