### ISSUE TITLE
Write Unit Test & Update Asserts for crop_image

### ISSUE THREAD

**Issue by lwasser** [earthlab/earthpy#34] opened 2018-10-22 20:43 UTC

**Comment by mbjoseph** [comment] 2018-10-24 02:01
Note to whoever writes these tests, please consider the edge case of cropping using an extent that is just a point (with zero area), e.g., something like the result of 

```python
earthpy.spatial.extent_to_json([0, 0, 0, 0]) # [xmin, ymin, xmax, ymax]
```

For completeness, there is also the edge case of when the extent is a line, e.g., 

```python
earthpy.spatial.extent_to_json([0, 0, 1, 0])
```

**Comment by mbjoseph** [comment] 2018-12-06 19:09
This issue is a duplicate of  #70

**Closed by mbjoseph** 2018-12-06 19:09 UTC
