### ISSUE TITLE
Support for clipping multi part polygon's in earthpy 

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earthpy#236] opened 2019-02-18 16:44 UTC
When calling earthpy.clip, if either the clip feature or the source feature have "multi" in their geometry, the clip fails. This creates the need to use .explode, and then .reset_index(level=[1]) on all parts of the clip for the function to work. We should look into if there is a way to do this in the function itself. @lwasser

**Comment by lwasser** [comment] 2019-02-18 20:00
@nkorinek this is a great issue. thank you!! can you create a reproducible example that we can use to test this? I think the tests for clip might help you do that :) Please add that example to your issue text above and we can explore the fix that you are suggesting !! thank you!

Also please format your issues to use `CODE SYNTAX` . this makes them easier to read. notice you can make text appear to be "code" with a grey background using the ticks. we used these in our jupyter notebooks too in class. When you add that example please clean up your issue and ensure the example code is also highlighted ! You can click the "preview" tab to see what your issue looks like before submitting it!

**Comment by nkorinek** [comment] 2019-02-20 15:44
Can do! 

So the example I noticed this on was in the fourth week notebook. The old code was this, where both variables are a shapefile with "Multi" somewhere in the geometry:
```
ne_roads = gpd.read_file('data/spatial-vector-lidar/global/ne_10m_roads/ne_10m_roads.shp')
ca_cty = gpd.read_file('data/spatial-vector-lidar/california/ca_counties/CA_Counties_TIGER2016.shp')
ca_cty_albers = ca_cty.to_crs({'init': 'epsg:5070'})
ne_roads_albers = ne_roads.to_crs({'init': 'epsg:5070'})
three_counties = ca_cty_albers[ca_cty_albers['NAME'].isin(["Siskiyou", "Modoc", "Del Norte"])]
ca_roads = cl.clip_shp(ne_roads_albers, three_counties)
```

The required fix looks like this (all the variables are read in the same way). As you can see, it's a lot more complicated. 

```
three_counties = three_counties.explode()
three_counties = three_counties.reset_index(level=[1])
ne_roads_albers = ne_roads_albers.explode()
ne_roads_albers = ne_roads_albers.reset_index(level=[1])
ca_roads = cl.clip_shp(ne_roads_albers, three_counties)
```

Hope that helps to clarify!

**Comment by mirob9363** [comment] 2019-02-20 16:18
test ping

**Comment by joemcglinchy** [comment] 2019-02-20 17:24
Thanks @nkorinek!! In this example, there are 30 geometries in the `ne_roads_albers` class which are multipart geometries (MULTILINESTRING vs. LINESTRING). You'll notice that there is a new column in the clipped feature called `level_1`, which is the index associated with exploding the feature. I'm happy to see the columns are copied over for each exploded feature, so we don't need to worry about that. 

I guess the question now is, what do we want to do for default behavior of handling features provided to the `clip_shp` function?? We could test for multipart geometries, as we are doing now, and if they exist run this bit of code to do a behind-the-scenes conversion to singlepart geometries. This would allow for flexibility in the input feature geometries, but perhaps if we do this we should add some kind of warning or something telling the user which feature is being converted to singlepart.


Cheers,
Joe

**Comment by nkorinek** [comment] 2019-02-27 16:34
@joemcglinchy Hi, so sorry for the late reply! Ya, that sounds like a good idea! I think a warning would be fair. I'm trying to think of a way to get the user to allow a clip on a multipart feature. My first thought was to get an input from the user to move along, but that would obviously be very interrupting to workflow for any notebooks or jobs made with clip. So I was thinking that we have an additional boolean argument in clip which is called `allow_multi` or something, which is default set to `false`. If set to false, the function could spit out the warning and instructions on how to allow multipart features, and then end the operation. If set to true, it could still spit out a warning, but it would also do the above fix to clip the multipart features. Let me know your thoughts on this, and if you would like me to try and implement this or not.

**Comment by lwasser** [comment] 2019-03-06 19:05
@joemcglinchy @nkorinek and i chatted about this a bit more today. he is going to provide an example here of how the function could work but right now we are considering

1. having an argument to allow multi-part polys. this would ensure that users know we are "messing" with the geometry on the back end so there are no surprises
2. If that argument is `True`, then we will 
   - explode the multi geometries
   - clip and then 
   - put the geometries back together again with the original indexing as multi features. 

Do you have any thoughts on the above? does it sound reasonable?

**Comment by joemcglinchy** [comment] 2019-03-06 22:45
sorry for the late reply guys! I think the above does sound reasonable. Is the reassembly of single-part to multi-part via index something straightforward to do in geopandas? Would you use `multipart 
 = singlepart.dissolve(by='index')`?

**Comment by lwasser** [comment] 2019-03-07 15:39
oooh @nkorinek i think found a slightly different approach. he was going to look into options.
 @joemcglinchy example looks very straight forward. does that work Nathan??

**Comment by nkorinek** [comment] 2019-03-07 19:49
I'll try it out with my example code and see if that restores the polygons to their original states. Looks really good and promising!

**Comment by nkorinek** [comment] 2019-03-07 21:42
Alright, I have done a fair amount of poking around, and here is what I've found. 

It is possible to get the data back into it's original state. To clip a multipart feature and change it back, a few steps are necessary. Before exploding the dataframe, it is good to store the columns with 

`cols = df.columns.tolist()`

Explode reorders the columns, so to put them back in the right order after the explode is ran, it is easiest just to have them from the original dataframe. After the columns are stored, 

`df.explode().reset_index(level=[1])`

must be run. After this step, you can clip the feature with multipart geometries no problem. After the clip is run, in order to revert the changes, 

`df = df.dissolve(by=[df.index]).drop(columns='level_1')[test_cols]` 

needs to be run, to recreate the multipart geometries and to make the column names identical again. 

There is a small caveat on all of this, however. `df_orig.equals(df_changed)` fails to pass with true, meaning the two dataframes are not actually identical pre and post operation. After looking into this, I discovered that the only differences lie in the geometry column. The difference is that the pointer changes for the geometry if it's exploded and then remerged, since it is technically a new line. The point location is the only difference. I wouldn't think this should be a huge concern. If it is let me know. Anyways, that's what I've found, thoughts? @lwasser @joemcglinchy

**Comment by joemcglinchy** [comment] 2019-03-07 22:11
@nkorinek can you elaborate by what you mean for the pointer location? do you mean location in memory?

**Comment by joemcglinchy** [comment] 2019-03-07 22:14
i did a test with the ne_roads dataset, recording which rows contained MULTILINESTRING in the geometry column, stored in a list called `mp_inds`. Using those geometries (`mp_subset`), I ran the following code:

```
test_mp = mp_subset.copy()
cols = test_mp.columns.tolist()
test_sp = test_mp.explode().reset_index(level=[1])
test_mp2 = test_sp.dissolve(by=[test_sp.index]).drop(columns='level_1')[cols]
test_mp.equals(test_mp2)
```
which returns `False`. However, if I check the geometries with this block of code:

```
for i in mp_inds:
    orig_geom = test_mp.geometry[i]
    new_geom = test_mp2.geometry[i]
    
    print(orig_geom.difference(new_geom).wkt)
```
I get GEOMETRYCOLLECTION EMPTY for each one, suggesting that the geometries are equal.

**Comment by lwasser** [comment] 2019-05-09 19:35
Leah will add some screenshots of the plots associated wtih this.

**Comment by lwasser** [comment] 2019-05-09 20:29
# Code
```

# make clip object
poly_inters = Polygon([(0, 0), (0, 10), (10, 10), (10, 0), (0, 0)])
gdf = gpd.GeoDataFrame([1], geometry=[poly_inters], crs={"init": "epsg:4326"})
gdf["attribute1"] = ["roads"]
single_rect_poly_gdf=gdf.copy()

# make multi obj
multi_poly = donut.unary_union
out_df = gpd.GeoDataFrame(gpd.GeoSeries(multi_poly), crs={"init": "epsg:4326"})
out_df = out_df.rename(columns={0: "geometry"}).set_geometry("geometry")
out_df["attr1"] = "pools"
multi_gdf = out_df.copy()


# Original Data using the above test
f, (ax, ax1, ax2) = plt.subplots(1, 3)
single_rect_poly_gdf.plot(edgecolor="purple", color="white", ax=ax1)
ax.set_title("Multi part poly data")
multi_gdf.plot(ax=ax)
ax1.set_title("Clip polygon")
ax.set_xlim([-20, 20])
ax.set_ylim([-20, 20])
ax1.set_xlim([-20, 20])
ax1.set_ylim([-20, 20])

ax2.set_title("Data Overlayed")

single_rect_poly_gdf.plot(edgecolor="purple", color="white", ax=ax2)
multi_gdf.plot(ax=ax2)
ax2.set_xlim([-20, 20])
ax2.set_ylim([-20, 20])
plt.show()

# clip the data
clip = cl.clip_shp(multi_gdf, single_rect_poly_gdf)

## Clipped Data
f, ax=plt.subplots()
clip.plot(color="purple", ax=ax)
ax.set_title("Clipped Data - notice there are two slivers here\n These are returned as lines")
plt.show()
```

Below are the original data:

![image](https://user-images.githubusercontent.com/7649194/57483984-2a647200-7265-11e9-9c40-2706a84e03d0.png)

## When you clip the data you get the following:
The output is 4 objects - two are polygons but two are lines
![image](https://user-images.githubusercontent.com/7649194/57484114-77484880-7265-11e9-98ef-054610764f16.png)

```
                                           geometry  attr
0  (POLYGON ((10 4.131875511680132, 10 0, 5.45910...  pool
1  (LINESTRING (0 0, 5.459108512695298 0), LINEST...  pool
```
Right now clip recombines the multi poly into a new polygon and also combines the lines into linestring objects. the attributes are maintained. This preserves the data. However it could be problematic for users if they export. BUT it does maintain the integrity of the data. I could show a warning that could be turned off if it gets annoying as an option.

**Comment by nkorinek** [comment] 2019-05-14 19:32
[This pr](https://github.com/earthlab/earthpy/pull/317) addresses this issue, but it is still in active review.

**Comment by lwasser** [comment] 2019-05-21 16:24
thanks @nkorinek i think we are close to merging it too!!

**Comment by lwasser** [comment] 2019-05-23 16:56
merged!!!

https://github.com/earthlab/earthpy/pull/317

**Closed by lwasser** 2019-05-23 16:56 UTC
Labels: enhancement
